INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (0, 'Committee Bill', 'CB');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (1, 'Bill', 'B');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (2, 'Resolution', 'R');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (3, 'Concurrent Resolution', 'CR');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (4, 'Joint Resolution', 'JR');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (5, 'Joint Resolution Constitutional Amendment', 'JRCA');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (6, 'Executive Order', 'EO');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (7, 'Constitutional Amendment', 'CA');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (8, 'Memorial', 'M');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (9, 'Claim', 'CL');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (10, 'Commendation', 'C');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (11, 'Committee Study Request', 'CSR');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (12, 'Joint Memorial', 'JM');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (13, 'Proclamation', 'P');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (14, 'Study Request', 'SR');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (15, 'Address', 'A');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (16, 'Concurrent Memorial', 'CM');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (17, 'Initiative', 'I');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (18, 'Petition', 'PET');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (19, 'Study Bill', 'SB');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (20, 'Initiative Petition', 'IP');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (21, 'Repeal Bill', 'RB');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (22, 'Remonstration', 'RM');
INSERT INTO type (bill_type_id, bill_type_name, bill_type_abbr) VALUES (23, 'Committee Bill', 'CB');